### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by asucra** [asucra/oko_log#26]
### 概要
日常で感じる怒りを記録（アンガーログ）するアプリです
怒りを記録・視覚化することで、怒りをコントロールする手助けを目的とします

### MVPリリース時実装予定機能
- [ ] ログイン・ログアウト機能
- [ ] 退会機能
- [ ] ゲストログイン機能
- [ ] ユーザー情報編集機能
- [ ] アンガーログ記録機能
- [ ] タグづけ機能
- [ ]  アンガーログ一覧
- [ ] ユーザー登録機能
- [ ] パスワード再設定機能

### MVPリリース時必要ページ
- [ ] トップページ
- [ ] 新規ユーザー登録ページ（登録方法選択画面）
- [ ] ログインページ
- [ ] 新規ユーザー登録情報入力ページ
- [ ] パスワードリセット依頼ページ
- [ ] パスワードリセット受付完了ページ
- [ ] ログイン後ホーム画面
- [ ] アンガーログ入力ページ
- [ ] アンガーログ一覧ページ
- [ ] アンガーログ編集ページ
- [ ] ユーザー情報編集ページ
- [ ] メールアドレス変更ページ
- [ ] パスワード変更ページ
- [ ] パスワード変更受付完了ページ

以上、ご確認どうぞよろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
GitHubProjectsが確認できませんでしたので、こちらご確認いただいてもよろしいですか？
(作成してあるが見れない場合、private設定にしてあることが多いです。)
よろしくお願いします。

**Comment by asucra** [comment]
tomita_kazuki先生
コメントいただきありがとうございます。
ご指摘のとおりprivate設定となっていました。申し訳ないです。
  
publicに変更いたしました。
ページが確認できるか、再度確認いただけると幸いです。
どうぞよろしくお願いいたします。

**Comment by ky0613** [comment]
ご提出ありがとうございます。
以下のようにprojectsがリポジトリに紐づけられていないため対応をお願いします。
[![Image from Gyazo](https://i.gyazo.com/6325fae6f5a03d0cec6a77cb0fca7df4.png)](https://gyazo.com/6325fae6f5a03d0cec6a77cb0fca7df4)

**Comment by asucra** [comment]
ky0613先生

度々申し訳ございません。
Oko_logリポジトリからprojectsを紐付けすることができませんでした。
projectsをpublicに変更したのですが、リポジトリのprojectsから既存のprojectsを
検索しようとしても出でこない状態です。
自己解決が難しそうなので技術面談できる場所に移動後、面談を申し込もうと思います。
  
申し訳ございませんが、一旦、projectsのURLを共有させていただきますのでこちらで
内容が確認できるか一旦ご確認いただけないでしょうか。申し訳ございません。
https://github.com/users/asucra/projects/1/views/1

**Comment by ky0613** [comment]
頂いたリンクは確認可能です！
以下の赤枠部分からの追加ができないということでしょうか？
[![Image from Gyazo](https://i.gyazo.com/87073b04834c5752eeba1ad67becebcb.png)](https://gyazo.com/87073b04834c5752eeba1ad67becebcb)

**Comment by asucra** [comment]
ky0613先生
コメントいただきありがとうございます。
結果的に追加できました。ありがとうございました。

link a projectを押下しても何も反応がなかったのですが、技術面談依頼しようと
図書館から帰宅して、再度PCを開いてやってみたところ追加できました。
ありがとうございます。

ご迷惑をおかけいたしました。
ご確認をどうぞよろしくお願いいたします。

**Comment by tmtkzk0823** [comment]
確認できました！
概ね良さそうです。
LGTMです！

**Comment by asucra** [comment]
tomita_kazuki先生
ご確認いただきありがとうございました。
