### ISSUE TITLE
レビュー用issue

### ISSUE THREAD

**Issue by asucra** [asucra/oko_log#69]
レビューを依頼いたします。どうぞよろしくおねがいいたします。
  
## 各種情報
サービス名：Oko_log
サービスURL：https://oko-log-app-ffa0745e6641.herokuapp.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x]  ログイン機能
- [x]   ログアウト機能
 - [ ]  退会機能
 - [ ]  ゲストログイン機能
 - [x]  ユーザー登録機能
 - [x]  ユーザー情報編集機能
 - [ ]  パスワード再設定機能
 - [x]  アンガーログ記録機能
 - [x]  アンガーログ一覧機能
- [x]   アンガーログ編集機能
 - [x]  アンガーログ削除機能
 - [x]  タグ登録機能
 - [x]  タグ編集機能
 - [x]  タグ削除機能

## READMEレビュー時から変更した機能
MVPリリース時点で作らなくなった機能について
面談を通して退会機能、ゲストログイン機能、パスワード再設定機能は本リリースまでに完成することとなりました。

## サービスイメージがわかるようなスクリーンショット等
管理画面は現在用意はありません。
スクリーンショット1

![Image](https://github.com/asucra/oko_log/assets/146820215/12c09bc2-deef-4f24-8292-ccbb132569cf)
  
  
スクリーンショット2

![Image](https://github.com/asucra/oko_log/assets/146820215/f624c414-1f52-430a-bc46-a1d758951b68)

以上、どうぞよろしくお願いいたします。

**Comment by ippei-shimizu** [comment]
下記機能について確認ができませんでした。
ご確認の上、必要であれば修正等を行ってください。
もし実装できているのであれば、コメントに確認手順を詳しく記載してください。
上記いずれかのご対応の上、RUNTEQアプリから再提出してください。

---

- アンガーログ入力画面にて、「日時」を「今日」にするとバリデーションエラーが発生して記録することができませんでした。
ユーザーが怒りの感情が発生したタイミングで記録するユースケースも想定されるため、「今日」の日時でも記録できる方が良いと思いました。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/c4380a6f4defb03eba92690c54cdf35c.png)](https://startup-technology.gyazo.com/c4380a6f4defb03eba92690c54cdf35c)

**Comment by asucra** [comment]
ippei-shimizu先生
レビューをいただきありがとうございます。

修正が完了いたしましたら再度レビュー依頼をさせていただきます。
  
ありがとうございます。

**Comment by asucra** [comment]
バリデーションをカスタムバリデーションに修正しました。

- バリデーションで利用していたTime.currentが意図しないタイミングで現在時刻を取得していたため、
データ登録時に現在時刻を取得するようにコードを変更しました

**Comment by shota-hope** [comment]
修正ありがとうございます。
確認ができました、LGTMです！
引き続きがんばってください。

**Comment by asucra** [comment]
おおの先生
ご確認いただきありがとうございました。
引き続き頑張ります。
